# rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-cleanup-rolebinding
  namespace:  second-namespace  
subjects:
- kind: ServiceAccount
  name: pod-cleanup-sa  
  namespace: default  
roleRef:
  kind: Role
  name: pod-cleanup-role
  apiGroup: rbac.authorization.k8s.io