# role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-cleanup-role
  namespace: second-namespace  
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]